spring:
  application:
    name: lotus-api-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lotus
    username: root
    password: root

jimmer:
  show-sql: true
  language: kotlin
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect

lotus:
  security:
    anno-url:
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-ui.html
      - /doc.html
      - /webjars/**
      - /favicon.ico
      - /auth/login